services:
  nginx:
    tty: true
    image: nginx:1.26
    container_name: habittracker_nginx
    working_dir: /app
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:8080"
    depends_on:
      - react_frontend
      - dotnet_webapi

  dotnet_webapi:
    tty: true
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: dotnet_webapi
    working_dir: /app
    volumes:
      - ./backend:/app
    command: ["dotnet", "run"]

  react_frontend:
    tty: true
    image: node:22
    container_name: react_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - habittracker_front_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"

volumes:
  habittracker_front_modules:
