services:
  nginx:
    tty: true
    image: nginx:1.26
    container_name: habittracker_nginx
    working_dir: /app
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:8080"
    depends_on:
      - react_frontend
      - dotnet_webapi
      - mysql

  dotnet_webapi:
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    container_name: dotnet_webapi
    working_dir: /app
    volumes:
      - ./backend:/app
    command: ["dotnet", "run"]
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=habittracker

  react_frontend:
    tty: true
    image: node:22
    container_name: react_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - habittracker_front_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: habittracker
    volumes:
      - habittracker_mysql_data:/var/lib/mysql

volumes:
  habittracker_front_modules:
  habittracker_mysql_data:
