// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(HabitTrackerDbContext))]
    [Migration("20250309143237_add-seeds")]
    partial class addseeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("backend.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndsAt")
                        .HasColumnType("date");

                    b.Property<string>("MeasurementUnit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("StartsAt")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TargetPeriod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TargetValue")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndsAt = new DateOnly(2025, 4, 8),
                            MeasurementUnit = "kg",
                            StartsAt = new DateOnly(2025, 3, 9),
                            Status = "active",
                            TargetPeriod = "monthly",
                            TargetValue = 10,
                            Title = "Goal 1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            EndsAt = new DateOnly(2025, 1, 6),
                            MeasurementUnit = "kg",
                            StartsAt = new DateOnly(2025, 1, 1),
                            Status = "completed",
                            TargetPeriod = "weekly",
                            TargetValue = 20,
                            Title = "Goal 2",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            EndsAt = new DateOnly(2025, 4, 8),
                            MeasurementUnit = "kg",
                            StartsAt = new DateOnly(2025, 3, 9),
                            Status = "active",
                            TargetPeriod = "monthly",
                            TargetValue = 30,
                            Title = "Goal 3",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            EndsAt = new DateOnly(2025, 1, 6),
                            MeasurementUnit = "kg",
                            StartsAt = new DateOnly(2025, 1, 1),
                            Status = "completed",
                            TargetPeriod = "weekly",
                            TargetValue = 40,
                            Title = "Goal 4",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            EndsAt = new DateOnly(2025, 1, 6),
                            MeasurementUnit = "kg",
                            StartsAt = new DateOnly(2025, 1, 1),
                            Status = "abandon",
                            TargetPeriod = "weekly",
                            TargetValue = 50,
                            Title = "Goal 5",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("backend.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        });
                });

            modelBuilder.Entity("backend.Models.Goal", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("Goals");
                });
#pragma warning restore 612, 618
        }
    }
}
